### ISSUE TITLE
Create FAQ page 

### ISSUE THREAD

**Issue by mike-ferguson** [brain-score/brain-score.web#239] opened 2024-02-14 16:16 UTC
Creates a page for an FAQ

- [ ] Add path in URLs.py
- [ ] Add user.py method
- [ ] Create HTML page for FAQ
- [ ] Style HTML Page 
- [ ] Add actual material for FAQ @pellegreene 
- [ ] Point "new issues" to a community page

**Comment by kvfairchild** [comment] 2024-02-16 13:29
Closing as duplicate of #232

**Closed by kvfairchild** 2024-02-16 13:29 UTC
